version: "3"
services:
#    nginx:
#        image: nginx:latest
#        ports:
#            - "80:80"
#            - "443:443"
#        volumes:
#            - ./docker/nginx/local/nginx.conf:/etc/nginx/nginx.conf
#            - ./docker/nginx/local/site.conf:/etc/nginx/conf.d/site.conf
#            - ./:/var/www/symfony/
#        links:
#            - php
    php:
        build: docker/php7-fpm
        volumes:
            - ./:/var/www/symfony
        env_file:
            - ".env"
        links:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
#        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
