version: "3"
services:
    php:
        build: docker/php7-fpm
        container_name: ${PHP_CONTAINER}
        volumes:
            - ./:/var/www/symfony
        env_file:
            - ".env"
        links:
            - mysql
    mysql:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - ./docker/mysql/db:/var/lib/mysql
